
name: wazo-prometheus-exporter
namespace: wazoplatform
version: 0.0.1
author: Wazo authors
display_name: Prometheus Metrics
min_wazo_version: 23.02
tags:
  - prometheus
  - metrics
homepage: https://github.com/wazo-platform/wazo-prometheus-exporter-plugin
debian_depends:
  - python3-prometheus-flask-exporter
