name: wazo-prometheus-exporter
namespace: wazoplatform
version: 0.0.6
author: Wazo authors
display_name: Prometheus Metrics
min_wazo_version: 25.15
tags:
  - prometheus
  - metrics
homepage: https://github.com/wazo-platform/wazo-prometheus-exporter-plugin
debian_depends:
  - python3-build
  - python3-pip
  - python3-venv
  - python3-prometheus-flask-exporter
  - python3-starlette-exporter
  - prometheus-nginx-exporter
  - docker.io
